### ISSUE TITLE
Add a way to add prefixes to labels. Like for example a valuta symbol.

### ISSUE THREAD

**Issue by Flexxkii** [maxshuty/accessible-web-components#2]
I want the label to be displayed as a price indicator.

Adding :after to _.range-span-label_ elements doesn't seem to work for some unknown reason.

**Comment by maxshuty** [comment]
Hi @Flexxkii - sorry for the delayed reply. I did not have my notification settings correctly set for this repo.

The styling you were trying to achieve likely was not working due to the nature of the shadow DOM. 

I will try coming up with a solution to add prefixes to labels, however, it may be tricky once people want to inject icons and other things in there. I will see what I can come up with and update this once complete.

Thanks!

**Comment by maxshuty** [comment]
Fixed [here](https://github.com/maxshuty/accessible-web-components/pull/7), thanks @Flexxkii!

**Comment by Flexxkii** [comment]
> Fixed [here](https://github.com/maxshuty/accessible-web-components/pull/7), thanks @Flexxkii!

You're the best!

I wish you a happy new year <3
