### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FelipeZago14** [maxshuty/accessible-web-components#21]
Hello, Can I make the slide past a certain value? For example, scrolling the slide from 1000 to 1000

**Comment by maxshuty** [comment]
Hi @FelipeZago14. I'm not sure I understand the full ask here do you mean so that both of the sliders are equal to one another? If so that is not possible since it's a _range_ slider. However, if you need this functionality there is a slight work around you can use `inputs-for-labels` and then you could set them equal using the inputs. You can view examples of that on the [demo](https://maxshuty.github.io/accessible-web-components/).

Let me know if that answers the question. Thanks!

**Comment by FelipeZago14** [comment]
I want the range to move in steps of 50 thousand instead of going one by one, is the only way to do that using the onChange event or is there something on the lib?

**Comment by maxshuty** [comment]
Got it, currently the slider does not support stepping in anything other than 1. If you add a feature request I can try and work on this. Alternatively if you need this asap you could fork it and if you look inside the library you'll see where the steps are set. The problem is that there appears to be a bug where if you change these values to something other than 1 then both values update when either the minimum range selector or maximum is selected

```
      <label id="${constants.MIN_LABEL_ID}" for="${constants.MIN}">Minimum</label> 
      <input id="${constants.MIN}" class="range-input" name="${constants.MIN}" type="range" step="1" />
      <label id="${constants.MAX_LABEL_ID}" for="${constants.MAX}">Maximum</label>
      <input id="${constants.MAX}" class="range-input" name="${constants.MAX}" type="range" step="1" />
```
